---
- src: bertvv.samba
- src: cloudalchemy.node-exporter
- src: https://github.com/dev-sec/ansible-os-hardening
  name: dev-sec.os-hardening
  version: master
- src: https://github.com/dev-sec/ansible-ssh-hardening
  name: dev-sec.ssh-hardening
  version: master
- src: geerlingguy.docker
- src: geerlingguy.firewall
- src: geerlingguy.nfs
- src: geerlingguy.ntp
- src: geerlingguy.pip
- src: geerlingguy.repo-epel
- src: geerlingguy.security
- src: geerlingguy.swap
- src: rvm.ruby
- src: yatesr.timezone

- src: vladgh.common
- src: vladgh.hashicorp
- src: vladgh.qemu-guest-agent
- src: vladgh.shellcheck
- src: vladgh.smtp
