---
# System
timezone: US/Central

# Accounts
local_groups:
  - name: admins
    gid: 8236
    system: yes
    sudo: yes
  - name: vgh
    gid: 8446
local_users:
  - name: vlad
    comment: Vlad Ghinea
    uid: 8523
    groups:
      - admins
      - vgh
    append: 'yes'
    shell: /bin/bash
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me

# OS Hardening
sysctl_overwrite:
  # Enable IPv4 traffic forwarding
  net.ipv4.ip_forward: 1
  # Do not disable IPv6
  net.ipv6.conf.all.disable_ipv6: 0
  # Enable IPv6 traffic forwarding
  net.ipv6.conf.all.forwarding: 1
  # Increase the amount of inotify watchers
  fs.inotify.max_user_watches: 524288
  # Do not change the default PTRACE value
  kernel.yama.ptrace_scope: 0

# SSH Hardening
# Needed for Duplicacy SFTP
sftp_enabled: true
# Needed for the bastion host or for Visual Studio Code Remote SSH Connection
ssh_allow_tcp_forwarding: 'yes'

# Security
security_autoupdate_enabled: true
security_fail2ban_enabled: true

# # Firewall
# firewall_allowed_tcp_ports:
#   - '22' # SSH
#   - '9100' # Prometheus
# firewall_allowed_udp_ports:
#   - '9473' # WireGuard
# firewall_additional_rules:
#   # WireGuard rules (IPv4 & IPv6)
#   - "iptables -A FORWARD -i wg0 -j ACCEPT"
#   - "iptables -t nat -A POSTROUTING -o {{ ansible_default_ipv4.alias }} -j MASQUERADE"
#   - "ip6tables -A FORWARD -i wg0 -j ACCEPT"
#   - "ip6tables -t nat -A POSTROUTING -o {{ ansible_default_ipv4.alias }} -j MASQUERADE"

# EMail
postfix_relayhost: smtp.sendgrid.net
postfix_relayhost_port: 587
postfix_relaytls: true
postfix_smtp_tls_cafile: /etc/ssl/certs/ca-certificates.crt
postfix_sasl_user: apikey
postfix_sasl_password: "{{ vault_postfix_sasl_password }}"
postfix_aliases:
  - user: root
    alias: vlad@ghn.me
postfix_header_checks:
  - pattern: '/From:.*/'
    action: 'REPLACE'
    text: 'From: Vlad <vlad@ghn.me>'

# Packages
additional_packages:
  - trash-cli

# WireGuard
wireguard_server: "{{ vault_wireguard_server }}"
wireguard_clients: "{{ vault_wireguard_clients }}"
