---
# Ansible
deploy_ssh_rsa: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDmv0M0KB/ZFGaja4p7A7f5p3cnuSckreV+RrnknhUZ/qKINRy+RgKNDNHSlqNm1B8btOuHrNfh13nVfoOuO/wQfr3J6Pk5UvZlv97MZi6FjFj4JhBQbegxfWmidiBMRJiQvwOYo3YrnUxh/bQEdGaBvR2z83qlmgoLvvgbFL0uuQeWcEfvarsLur/+CpsZwm1U5fVF28/mTd4cI/nE5V5NpD+nThxB7ZnNiFjb9+95UeBy38OCtVpLBw/G6kGr6e2Q/mm6Yf8tIsQMLAX57ReK+DA46jHjAfhWKVEarne8hPyLwbJQcuugkEUb5hia8HT+9aYln7as4Sgv3TPabmHUGs8/7n4//MK6x8ZJWci1+lXSNFM4RI5uo/eHN5a1i0nxUpjXeWJC2RptB4oKonLQECDUQAhtmwlvvf0LBS26fX90B/hAs8YUiKgbutyNCgUFdCzYbEmxn37v1hiy70CdTN1yfmnDtyaV65Ks62gwYEobCSg6Qqt23iSmJX84s5OciaGdym91kVkWkt9WSO3RQcUCLEWHFfHNLRWzi2uiHKJvvY5ZHPUsVYPRrr1g2/JBp+0jlqjbRQ+phin1DqVak2750PH9su+C5Ox1YAL9TfDrhZplgwbB6iUru4AYGke+CJo0mrDQvCPru67Qg7BovTtWDoI6wrSKYbzT6HCnuw== Deploy

# System
timezone: US/Central

# Accounts
local_groups:
  - name: admins
    system: yes
    sudo: yes
local_users:
  - name: vlad
    comment: Vlad Ghinea
    groups: admins
    append: yes
    shell: /bin/bash
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me

# DNS
cloudflare_email: "{{ vault_cloudflare_email }}"
cloudflare_api_token: "{{ vault_cloudflare_api_token }}"
cloudflare_dns_records:
  - zone: ghn.me
    type: A
    record: vdev.home
    value: 192.168.1.10

# Slack
slack_token: "{{ vault_slack_token }}"
