---
# System
timezone: US/Central

# Accounts
accounts:
  - name: vlad
    comment: Vlad Ghinea
    groups: admins
    append: 'yes'
    shell: /bin/bash
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me
