---
# Development

# Accounts
accounts:
  - name: vlad
    comment: Vlad Ghinea
    groups: admins
    append: 'yes'
    shell: /bin/zsh
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me

# Docker
docker_users:
  - vlad

# Cron Jobs
cron_jobs:
  - name: Docker CleanUp
    minute: '2'
    hour: '2'
    job: docker system prune --force 2>&1 | /usr/bin/logger -t DockerCleanUp

# Hashicorp Packages
packer_install: 'yes'
terraform_install: 'yes'
vault_install: 'yes'

# # Ruby
# rvm1_rubies: ['ruby-2.7.0']
# rvm1_user: 'vlad'
# rvm1_rvm_version: 'stable'

# Shellcheck
shellcheck_install: 'yes'

# Apt repositories
apt_repositories:
  - name: GIT
    repo: ppa:git-core/ppa

# Mount points
mount_points:
  - name: DataStore
    path: /data/store
    src: 192.168.1.11:/data/store
    opts: hard,rsize=1048576,wsize=1048576,timeo=600,retrans=2,_netdev
    fstype: nfs
    owner: vlad
    group: 115
