---
# System
timezone: US/Central

# Accounts
local_groups:
  - name: admins
    gid: 8236
    system: yes
    sudo: yes
  - name: vgh
    gid: 8446
local_users:
  - name: vlad
    comment: Vlad Ghinea
    uid: 8523
    groups:
      - admins
      - vgh
    append: 'yes'
    shell: /bin/zsh
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me

# Docker
docker_users:
  - vlad

# Cron Jobs
cron_jobs:
  - name: Docker CleanUp
    minute: '2'
    hour: '2'
    job: docker system prune --force 2>&1 | /usr/bin/logger -t DockerCleanUp

# Packages
additional_packages:
  - curl
  - libcurl4-openssl-dev
  - libssl-dev
  - gnupg
  - gpg-agent
  - htop
  - jq
  - tmux
  - unzip
  - vim
  - wget
  - golang
  - zsh
  - powerline
  - fonts-powerline
  - nmap
  - sshpass
  - qrencode
  - mlocate
  - trash-cli

# GitHub
github_hub_version: 2.14.2  # https://github.com/github/hub/releases
github_cli_version: 0.9.0  # https://github.com/cli/cli/releases

# PIP
pip_user_install_packages:
  - user: vlad
    packages:
      - ansible
      - ansible-lint
      - molecule
      - docker
      - boto3
      - flake8
      - pylint
      - ssh2
      - virtualenv
      - nvchecker
      - httpx
      - jsondiff
      - pyyaml
    state: latest

# EMail
postfix_relayhost: smtp.sendgrid.net
postfix_relayhost_port: 587
postfix_relaytls: true
postfix_smtp_tls_cafile: /etc/ssl/certs/ca-certificates.crt
postfix_sasl_user: apikey
postfix_sasl_password: "{{ vault_postfix_sasl_password }}"
postfix_aliases:
  - user: root
    alias: vlad@ghn.me
postfix_header_checks:
  - pattern: '/From:.*/'
    action: 'REPLACE'
    text: 'From: Vlad <vlad@ghn.me>'
