---
# Development

# Accounts
accounts:
  - name: vlad
    comment: Vlad Ghinea
    groups: admins
    append: 'yes'
    shell: /bin/zsh
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me

# Docker
docker_users:
  - vlad

# Cron Jobs
cron_jobs:
  - name: Docker CleanUp
    minute: '2'
    hour: '2'
    job: docker system prune --force 2>&1 | /usr/bin/logger -t DockerCleanUp

# Apt repositories
apt_repositories:
  - name: GIT
    repo: ppa:git-core/ppa

# SMTP
smtp_server_address: smtp.sendgrid.net
smtp_server_port: 587
smtp_from: Vlad <vlad@ghn.me>
smtp_user: apikey
smtp_password: "{{ vault_smtp_password }}"
