---
# System
timezone: US/Central

# Accounts
local_groups:
  - name: admins
    gid: 8236
    system: yes
    sudo: yes
  - name: vgh
    gid: 8446
local_users:
  - name: vlad
    comment: Vlad Ghinea
    uid: 8523
    groups:
      - admins
      - vgh
    append: 'yes'
    shell: /bin/bash
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me

# Mount points
mount_points:
  - name: Media
    path: /vpool/media
    src: 192.168.10.11:/vpool/media
    opts: soft
    fstype: nfs

# Packages
additional_packages:
  - trash-cli

# Docker
docker_users:
  - vlad

# Cron Jobs
cron_jobs:
  - name: Docker Maintenance
    minute: '3'
    hour: '3'
    job: docker system prune --all --force 2>&1 | /usr/bin/logger -t DockerMaintenance

# EMail
postfix_relayhost: smtp.sendgrid.net
postfix_relayhost_port: 587
postfix_relaytls: true
postfix_smtp_tls_cafile: /etc/ssl/certs/ca-certificates.crt
postfix_sasl_user: apikey
postfix_sasl_password: "{{ vault_postfix_sasl_password }}"
postfix_aliases:
  - user: root
    alias: vlad@ghn.me
postfix_header_checks:
  - pattern: '/From:.*/'
    action: 'REPLACE'
    text: 'From: Vlad <vlad@ghn.me>'
