# User accounts
---
- name: Provision DNS Records
  hosts: localhost
  become: yes
  tasks:
    - name: Create DNS records
      cloudflare_dns:
        zone: "{{ item.zone }}"
        type: "{{ item.type }}"
        record: "{{ item.record }}"
        value: "{{ item.value }}"
        proxied: "{{ item.proxied | default(omit) }}"
        account_email: "{{ cloudflare_email }}"
        account_api_token: "{{ cloudflare_api_token }}"
      with_items: "{{ cloudflare_dns_records }}"
