---
# Accounts
local_groups:
  - name: admins
    system: yes
    sudo: yes
  - name: vgh
    gid: 8844
local_users:
  - name: vlad
    comment: Vlad Ghinea
    groups:
      - admins
      - vgh
    append: 'yes'
    shell: /bin/bash
    authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ vlad@ghn.me
  - name: alice
    shell: /usr/sbin/nologin
    create_home: no
    groups:
      - vgh

# Mount points
mount_points:
  - name: WD2T
    path: /data
    src: UUID="78056259-01e8-4d4b-bb3c-edc4ed1e8171"
    fstype: ext4
  - name: EncryptedDataStore
    path: /data/encrypted
    src: UUID="0b86bdb1-33b7-4a47-810b-ebc0392f63f4"
    fstype: ext4

# NFS Server
nfs_exports:
  - '/data/store *(rw,sync,all_squash,anonuid=1000,anongid=1000,no_subtree_check)'
  - '/data/vm *(rw,sync,all_squash,anonuid=1000,anongid=1000,no_subtree_check)'

# Samba Server
samba_netbios_name: VDS
samba_server_string: "Vlad Data Store"
samba_workgroup: WORKGROUP
samba_load_printers: 'no'
samba_users: "{{ vault_samba_users }}"
samba_shares:
  - name: DataStore
    comment: 'Data Store'
    path: '/data/store'
    public: 'no'
    writable: 'yes'
    browseable: 'yes'
    valid_users: 'vlad alice @vgh'
    owner: 'vlad'
    group: 'vgh'
    create_mode: '0664'
    force_create_mode: '0664'
    directory_mode: '0775'
    force_directory_mode: '0775'
  - name: EncryptedDataStore
    comment: 'Encrypted Data Store'
    path: '/data/encrypted/store'
    public: 'no'
    writable: 'yes'
    browseable: 'no'
    valid_users: 'vlad alice @vgh'
    owner: 'vlad'
    group: 'vgh'
    create_mode: '0660'
    force_create_mode: '0660'
    directory_mode: '0770'
    force_directory_mode: '0770'
