---
# Mount points
mount_points:
  - name: WD2T
    path: /data
    src: UUID=78056259-01e8-4d4b-bb3c-edc4ed1e8171
    fstype: ext4

# NFS Server (115 is the group id for @sambashare)
nfs_exports:
  - '/data/store *(rw,sync,all_squash,anonuid=1000,anongid=115,no_subtree_check)'

# Samba Server
samba_netbios_name: VDS
samba_server_string: "Vlad Data Store"
samba_workgroup: WORKGROUP
samba_load_printers: 'no'
samba_mitigate_cve_2017_7494: 'no'
samba_users: "{{ vault_samba_users }}"
samba_shares:
  - name: DataStore
    comment: 'Data Store'
    path: '/data/store'
    writable: 'yes'
    browseable: 'yes'
    valid_users: 'vlad @sambashare'
    owner: 'vlad'
    group: 'sambashare'
    create_mode: '0664'
    force_create_mode: '0664'
    directory_mode: '0775'
    force_directory_mode: '0775'
  - name: EncryptedDataStore
    comment: 'Encrypted Data Store'
    path: '/encrypted_data/store'
    writable: 'yes'
    browseable: 'yes'
    valid_users: 'vlad'
    owner: 'vlad'
    group: 'vlad'
    create_mode: '0600'
    force_create_mode: '0600'
    directory_mode: '0700'
    force_directory_mode: '0700'
